replicaCount: 1
image:
  repository: quay.io/pires/docker-elasticsearch-kubernetes
  pullPolicy: IfNotPresent
  tag: 1.7.1-4

clustername: default-cluster

service:
  name: catalog-elasticsearch

labels:
  app: bluecompute
  tier: data
  micro: catalog

resources:
  limits:
    memory: 700Mi
  requests:
    memory: 350Mi

secretName: binding-refarch-compose-for-elasticsearch
