apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: bluecompute
    micro: elasticsearch
    tier: data
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  binding: {{ cat `{"uri": "http://` .Chart.Name `:9200/" }` | nospace | b64enc }}