replicaCount: 1

image:
  repository: ibmcase/bluecompute-catalog
  pullPolicy: IfNotPresent
  tag: latest

ibmcase-elasticsearch:
  replicaCount: 1
  image:
    repository: quay.io/pires/docker-elasticsearch-kubernetes
    pullPolicy: IfNotPresent
    tag: 1.7.1-4

  clustername: catalogdb
  
  service:
    name: catalog-elasticsearch

  labels:
    app: bluecompute
    micro: catalog
    tier: data
  
  resources:
    limits:
      memory: 700Mi
    requests:
      memory: 350Mi
  
  secretName: binding-catalog-elasticsearch

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

bluemix-compose-elasticsearch:
  apiKey:

  target:
    endpoint: api.ng.bluemix.net
    org:
    space:

  clusterName:
  
  service:
    name: catalog-elasticsearch
    type: compose-for-elasticsearch
    plan: Standard

global:
  bluemix:
    apiKey:
  
    target:
      endpoint: api.ng.bluemix.net
      org:
      space:
  
    clusterName:

tags:
  bluemix: false
  localdb: false
