replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

global:
  bluemix:
    apiKey:
  
    target:
      endpoint: api.ng.bluemix.net
      org:
      space:
  
    clusterName:
   
  
ibmcase-mysql:
  binding:
    name: binding-inventorydb-mysql

  labels:
    app: bluecompute
    tier: data
    micro: inventory
  
  dbname: inventorydb

  service:
    name: inventory-mysql

bluemix-messagehub:
  enabled: false
  apiKey:

  target:
    endpoint: api.ng.bluemix.net
    org:
    space:

  clusterName:
  
  service:
    name: orders-messagehub
    type: messagehub
    plan: standard
  
bluemix-compose-mysql:
  enabled: false
  apiKey:

  target:
    endpoint: api.ng.bluemix.net
    org:
    space:

  clusterName:
  
  service:
    name: inventorydb-mysql
    type: compose-for-mysql
    plan: Standard

