replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi
  
ibmcase-mysql:
  binding:
    name: binding-refarch-compose-for-mysql

  labels:
    app: bluecompute
    tier: data
    micro: inventory
  
  dbname: inventorydb

  service:
    name: inventorydb-mysql
