replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi
  
elasticsearch:
  secret: binding-refarch-compose-for-elasticsearch

mysql:
  secret: binding-refarch-compose-for-mysql
