apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: bluecompute
    micro: mysql
    tier: data
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      labels:
        app: bluecompute
        micro: mysql
        tier: data
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
              {
                  "name": "remove-lost-found",
                  "image": "busybox:1.25.0",
                  "command": ["rm", "-fr", "/var/lib/mysql/lost+found"],
                  "volumeMounts": [
                      {
                          "name": "data",
                          "mountPath": "/var/lib/mysql"
                      }
                  ],
                  "imagePullPolicy": "IfNotPresent"
              }
          ]'
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: mysql-password
        - name: MYSQL_USER
          value: {{ .Values.user }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database }}
        ports:
        - name: mysql
          containerPort: 3306
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
