apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: bluecompute
    micro: catalog
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector: 
    app: bluecompute
    micro: catalog
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"