apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.secretName }}
  labels:
{{ toYaml .Values.elasticsearch.labels | indent 4 -}}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  binding: {{ cat `{"uri": "http://` .Values.elasticsearch.service.name `:9200/" }` | nospace | b64enc }}
