apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: bluecompute
    micro: catalog
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: catalog
        tier: backend
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "test-elasticsearch",
            "image": "ibmcase/mysql-loader:latest",
            "imagePullPolicy": "IfNotPresent",
            "command": ["/bin/bash", "-c"], 
            "args": ["elastic_uri=`echo $elastic | jq .uri -r`; until curl -s ${elastic_uri}_cluster/health | jq .status | grep green; do echo waiting for elasticsearch; sleep 1; done"],
            "env": [{ 
              "name": "elastic",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "{{ template "elasticsearchBindingName" . }}",
                  "key": "binding"
                }
              }
            }]
          },
          {
            "name": "test-inventory-service",
            "image": "ibmcase/mysql-loader:latest",
            "imagePullPolicy": "IfNotPresent",
            "command": ["/bin/bash", "-c"], 
            "args": ["until curl http://inventory-service:8080; do echo waiting for inventory-service; sleep 1; done"]
          }
        ]'
    spec:
      containers:
      - name: catalog
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 8081
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: elastic
          valueFrom:
            secretKeyRef:
              name: {{ template "elasticsearchBindingName" . }}
              key: binding
